### ISSUE TITLE
Providing liquidity by submitting transaction clears order card

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#201]
![image](https://user-images.githubusercontent.com/38409137/99490394-99249000-291e-11eb-8436-e463bb80b642.png)

After I click submit order on the Provide liquidity order, the order card is cleared. I propose: don't clear the state, instead update the LP token balance once the transaction goes through.

**Comment by Alexangelj** [comment]
![image](https://user-images.githubusercontent.com/38409137/99614489-781b7800-29ce-11eb-9488-034fd17c82de.png)

**Comment by zachdt** [comment]
This is challenge due to how we track tab state.  I return to active positions because that includes the LP balance, and that updates on trade confirmation.  If I return to the order card, i need to pass a tab location prop that doesn't exist yet.  I'll keep this in mind for the future, can't prioritize this at the moment.

**Comment by zachdt** [comment]
Doing some major improvements to the sidebar that will hopefully reduce the clutter than the main screen currently has when doing a tx.

**Comment by zachdt** [comment]
This issue is somewhat stale now, we don't return to the order card but the positions card is now open by default.  Removing the item still shows balances after order submit, closing this for now.
